version: '3.4'


networks:
  ProductManagement.Api-dev:
    driver: bridge 


services:
  ProductManagement.Api:
    image: productmanagement.api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=nativeapps;username=admin;password=admin"
    networks:
      - ProductManagement.Api-dev  
      
  postgres_image:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seet.sql:/docker-entrypoint-initdb.d/seet.sql
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "nativeapps"
    networks:
      - ProductManagement.Api-dev
volumes:
  db_volume: